<?php
define('ACF_LITE',true);
if(function_exists("register_field_group")){
	register_field_group(array (
		'id' => 'acf_pagesingle-right-sidebar',
		'title' => 'Page/Single Right Sidebar',
		'fields' => array (
			array (
				'key' => 'field_53ea66cfcc236',
				'label' => 'Callouts',
				'name' => 'sidebar_callouts',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53ea66eccc237',
						'label' => 'Callout Type',
						'name' => 'field_type',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'info-box' => 'Small Single-Featured Vertical',
							'alert' => 'Vertical Button Callout',
							'graphic' => 'Graphic',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53ebaecb7106f',
						'label' => 'Field Title',
						'name' => 'field_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53ebaee171070',
						'label' => 'Field Color',
						'name' => 'field_color',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'blue' => 'Blue',
							'red' => 'Red',
							'green' => 'Green',
							'yellow' => 'Yellow',
							'grey' => 'Grey',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53ebb1a5094e9',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53ea66eccc237',
									'operator' => '==',
									'value' => 'info-box',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53ebb1bb094ea',
						'label' => 'Date',
						'name' => 'date',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53ea66eccc237',
									'operator' => '==',
									'value' => 'info-box',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53ebb1c4094eb',
						'label' => 'Supporting Info',
						'name' => 'supporting_info',
						'type' => 'textarea',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53ea66eccc237',
									'operator' => '==',
									'value' => 'info-box',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'field_53ebb1d4094ec',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'limiter',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53ea66eccc237',
									'operator' => '==',
									'value' => 'info-box',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'character_number' => 50,
					),
					array (
						'key' => 'field_53ebb1ee094ee',
						'label' => 'Link Text',
						'name' => 'link_text',
						'type' => 'select',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53ea66eccc237',
									'operator' => '==',
									'value' => 'info-box',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'Read More ≈' => 'Read More ≈',
							'See More ≈' => 'See More ≈',
							'More Info ≈' => 'More Info ≈',
							'Learn More ≈' => 'Learn More ≈',
							'More Events ≈' => 'More Events ≈',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53ebb1e1094ed',
						'label' => 'Link Url',
						'name' => 'link_url',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53ebb242094ef',
						'label' => 'Callout',
						'name' => 'callout',
						'type' => 'limiter',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53ea66eccc237',
									'operator' => '==',
									'value' => 'alert',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'character_number' => 50,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Callouts',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'resources',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_pagesingle-top-collouts',
		'title' => 'Page/Single Top Collouts',
		'fields' => array (
			array (
				'key' => 'field_53ea6126dbdfd',
				'label' => 'Callouts',
				'name' => 'top_callouts',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53ea61d9dbdfe',
						'label' => 'Callout Type',
						'name' => 'field_type',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'horizontal-callout-single' => 'Horizontal Button Callout',
							'horizontal-callout-multi' => 'Horizontal Callout',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53ea620ddbdff',
						'label' => 'Callout Color',
						'name' => 'field_color',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'blue' => 'Blue',
							'red' => 'Red',
							'green' => 'Green',
							'yellow' => 'Yellow',
							'grey' => 'Grey',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_53ea62bbdbe02',
						'label' => 'Callout Link',
						'name' => 'field_link',
						'type' => 'text',
						'instructions' => '<em>Is this callout linking somewhere? Add the URL here!<br>Is is not? Then ignore this!</em>',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53ea6252dbe00',
						'label' => 'Horizontal Callout - Single Title',
						'name' => 'horizontal_callout-single_title',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53ea61d9dbdfe',
									'operator' => '==',
									'value' => 'horizontal-callout-single',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => 25,
					),
					array (
						'key' => 'field_53ea6287dbe01',
						'label' => 'Horizontal Callout - Multi title',
						'name' => 'horizontal_callout-multi_title',
						'type' => 'limiter',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53ea61d9dbdfe',
									'operator' => '==',
									'value' => 'horizontal-callout-multi',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'character_number' => 50,
						'displayCount' => 1,
					),
				),
				'row_min' => '',
				'row_limit' => 2,
				'layout' => 'row',
				'button_label' => 'Add Callout',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'resources',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_sidebar-fields',
		'title' => 'Sidebar Fields',
		'fields' => array (
			array (
				'key' => 'field_53e8e03cf8143',
				'label' => 'Section Color',
				'name' => 'section_color',
				'type' => 'radio',
				'choices' => array (
					'blue' => 'Blue',
					'red' => 'Red',
					'green' => 'Green',
					'yellow' => 'Yellow',
					'grey' => 'Grey',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53e653a1de579',
				'label' => 'Sidebar Fields',
				'name' => 'sidebar_fields',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53e6549fde57a',
						'label' => 'Field Type',
						'name' => 'field_type',
						'type' => 'select',
						'required' => 1,
						'column_width' => '',
						'choices' => array (
							'' => '',
							'horizontal-callout-single' => 'Horizontal Button Callout',
							'horizontal-callout-multi' => 'Horizontal Callout',
							'listing-style-1-1' => 'Multi-Item Listing',
							'listing-style1-2' => 'Link Listing',
							'listing-style-2-1' => 'Calendar Feed',
							'listing-style-2-2' => 'Discussion Listing',
							'listing-style-3' => 'Listing Style 3',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53e6a9b51fd26',
						'label' => 'Field Color',
						'name' => 'field_color',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'blue' => 'Blue',
							'red' => 'Red',
							'green' => 'Green',
							'yellow' => 'Yellow',
							'grey' => 'Grey',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => '',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_53e7d292c3e52',
						'label' => 'Field Title',
						'name' => 'field_title',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e6549fde57a',
									'operator' => '==',
									'value' => 'listing-style-1-1',
								),
								array (
									'field' => 'field_53e6549fde57a',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
								array (
									'field' => 'field_53e6549fde57a',
									'operator' => '==',
									'value' => 'listing-style-3',
								),
							),
							'allorany' => 'any',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e78cb204251',
						'label' => 'Field Link',
						'name' => 'field_link',
						'type' => 'text',
						'instructions' => '<em>Is this callout linking somewhere? Add the URL here!<br>Is is not? Then ignore this!</em>',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e6549fde57a',
									'operator' => '==',
									'value' => 'horizontal-callout-single',
								),
								array (
									'field' => 'field_53e6549fde57a',
									'operator' => '==',
									'value' => 'horizontal-callout-multi',
								),
								array (
									'field' => 'field_53e6549fde57a',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
							),
							'allorany' => 'any',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e6561ede57b',
						'label' => 'Horizontal Callout - Single Title',
						'name' => 'horizontal_callout-single_title',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e6549fde57a',
									'operator' => '==',
									'value' => 'horizontal-callout-single',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => 25,
					),
					array (
						'key' => 'field_53e65662de57c',
						'label' => 'Horizontal Callout - Multi title',
						'name' => 'horizontal_callout-multi_title',
						'type' => 'limiter',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e6549fde57a',
									'operator' => '==',
									'value' => 'horizontal-callout-multi',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'character_number' => 50,
						'displayCount' => 1,
					),
					array (
						'key' => 'field_53eba128732fb',
						'label' => 'Multi-Item Listing',
						'name' => 'listing_style_1-1',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e6549fde57a',
									'operator' => '==',
									'value' => 'listing-style-1-1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53eba150732fc',
								'label' => 'Reference Other Post?',
								'name' => 'reference',
								'type' => 'true_false',
								'column_width' => 5,
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_53eba1c4732fd',
								'label' => 'Reference',
								'name' => 'reference_post',
								'type' => 'post_object',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53eba150732fc',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => 95,
								'post_type' => array (
									0 => 'post',
									1 => 'resources',
								),
								'taxonomy' => array (
									0 => 'all',
								),
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_53eba221732fe',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53eba150732fc',
											'operator' => '!=',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => 20,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53eba293732ff',
								'label' => 'Description',
								'name' => 'description',
								'type' => 'limiter',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53eba150732fc',
											'operator' => '!=',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => 20,
								'character_number' => 150,
							),
							array (
								'key' => 'field_53eba2b573300',
								'label' => 'Link URL',
								'name' => 'link_url',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53eba150732fc',
											'operator' => '!=',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53eba2d773301',
								'label' => 'Link Text',
								'name' => 'link_text',
								'type' => 'select',
								'column_width' => 20,
								'choices' => array (
									'Read More ≈' => 'Read More ≈',
									'See More ≈' => 'See More ≈',
									'More Info ≈' => 'More Info ≈',
									'Learn More ≈' => 'Learn More ≈',
									'More Events ≈' => 'More Events ≈',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
						),
						'row_min' => '',
						'row_limit' => 3,
						'layout' => 'row',
						'button_label' => 'Add Entry',
					),
					array (
						'key' => 'field_53e7d4ecca9fb',
						'label' => 'Listing Title',
						'name' => 'listing_title',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e6549fde57a',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e7d4b3ca9f9',
						'label' => 'urls',
						'name' => 'urls',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e6549fde57a',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53e7d553cfd22',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53e7d4c9ca9fa',
								'label' => 'URL',
								'name' => 'url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => 10,
						'layout' => 'table',
						'button_label' => 'Add Link',
					),
				),
				'row_min' => '',
				'row_limit' => 3,
				'layout' => 'row',
				'button_label' => 'Add Widget',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'top_level',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_full-width-fields',
		'title' => 'Full Width Fields',
		'fields' => array (
			array (
				'key' => 'field_53e8e1a189ce9',
				'label' => 'Full Width Callouts',
				'name' => 'full_width_callouts',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53e8e1c689cea',
						'label' => 'Field Type',
						'name' => 'field_type',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'listing-style-4' => 'Curated Listing',
							'8-column-featured' => 'Full-Width Featured Listing',
							'video' => 'Video Embedded',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53e8f364adba5',
						'label' => 'Field Color',
						'name' => 'field_color',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'blue' => 'Blue',
							'red' => 'Red',
							'green' => 'Green',
							'yellow' => 'Yellow',
							'grey' => 'Grey',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_53e8e20289ceb',
						'label' => 'Field Link',
						'name' => 'field_link',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e8e1c689cea',
									'operator' => '==',
									'value' => 'listing-style-4',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e922872ac76',
						'label' => 'Field Title',
						'name' => 'field_title',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e8e1c689cea',
									'operator' => '==',
									'value' => 'listing-style-4',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e8e22d89cec',
						'label' => 'Curated Listing',
						'name' => 'listing_style_4',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e8e1c689cea',
									'operator' => '==',
									'value' => 'listing-style-4',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53e8e24789ced',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'column_width' => 25,
								'save_format' => 'id',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_53e8e25d89cee',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => 37,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53e8e26289cef',
								'label' => 'Author',
								'name' => 'author',
								'type' => 'text',
								'column_width' => 38,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => 10,
						'layout' => 'table',
						'button_label' => 'Add Listing',
					),
					array (
						'key' => 'field_53e8e27589cf1',
						'label' => 'Full-Width Featured Listing',
						'name' => '8_column_featured',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e8e1c689cea',
									'operator' => '==',
									'value' => '8-column-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53e8e29c89cf2',
								'label' => 'Type',
								'name' => 'type',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'physical' => 'Physical',
									'online' => 'Online',
									'video' => 'Video',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_53e8e2dc89cf3',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53e8e2eb89cf4',
								'label' => 'Excerpt',
								'name' => 'excerpt',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'formatting' => 'br',
							),
							array (
								'key' => 'field_53e8e2f489cf5',
								'label' => 'Date',
								'name' => 'date',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53e8e29c89cf2',
											'operator' => '==',
											'value' => 'physical',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53e8e31389cf6',
								'label' => 'Url - link',
								'name' => 'url_link',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53e8e29c89cf2',
											'operator' => '==',
											'value' => 'online',
										),
										array (
											'field' => 'field_53e8e29c89cf2',
											'operator' => '==',
											'value' => 'video',
										),
									),
									'allorany' => 'any',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53e8e32a89cf8',
								'label' => 'Url - text',
								'name' => 'url_text',
								'type' => 'select',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53e8e29c89cf2',
											'operator' => '==',
											'value' => 'online',
										),
										array (
											'field' => 'field_53e8e29c89cf2',
											'operator' => '==',
											'value' => 'video',
										),
									),
									'allorany' => 'any',
								),
								'column_width' => '',
								'choices' => array (
									'Read More ≈' => 'Read More ≈',
									'See More ≈' => 'See More ≈',
									'More Info ≈' => 'More Info ≈',
									'Learn More ≈' => 'Learn More ≈',
									'More Events ≈' => 'More Events ≈',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_53e91de1fb545',
								'label' => 'Read More Link',
								'name' => 'read_more_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53e91de8fb546',
								'label' => 'Read More Text',
								'name' => 'read_more_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => 3,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_53eb7d82e8b65',
						'label' => 'Video Embedded',
						'name' => 'video_embedded',
						'type' => 'oembed',
						'instructions' => '<em>URL of video, NOT the embed code.</em>',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e8e1c689cea',
									'operator' => '==',
									'value' => 'video',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'preview_size' => 'medium',
						'returned_size' => 'large',
						'returned_format' => 'html',
					),
				),
				'row_min' => '',
				'row_limit' => 2,
				'layout' => 'row',
				'button_label' => 'Add widget',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/1-tpl.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'resources',
					'order_no' => 0,
					'group_no' => 3,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_four-column-fields-left',
		'title' => 'Four Column Fields - Left',
		'fields' => array (
			array (
				'key' => 'field_53e928253478b',
				'label' => 'Four Column Widgets',
				'name' => 'four_column_widgets-left',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53e928333478c',
						'label' => 'Field Type',
						'name' => 'field_type',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'single-featured' => 'Single Featured',
							'listing-style-1-1' => 'Multi-Item Listing',
							'listing-style1-2' => 'Link Listing',
							'listing-style-2-1' => 'Calendar Feed',
							'listing-style-2-2' => 'Discussion Listing',
							'listing-style-3' => 'Listing Style 3',
							'listing-style-4' => 'Curated Listing',
							'vertical-block' => 'Vertical Block',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53e9287a3478d',
						'label' => 'Field Title',
						'name' => 'field_title',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-1-1',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-3',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-4',
								),
							),
							'allorany' => 'any',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53ea14cf2c28c',
						'label' => 'Field Color',
						'name' => 'field_color',
						'type' => 'radio',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-1-1',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-3',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-4',
								),
							),
							'allorany' => 'any',
						),
						'column_width' => '',
						'choices' => array (
							'blue' => 'Blue',
							'red' => 'Red',
							'green' => 'Green',
							'yellow' => 'Yellow',
							'grey' => 'Grey',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_53e928d334794',
						'label' => 'Single Featured Item Title',
						'name' => 'single_featured_item',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e9290134795',
						'label' => 'Single Featured Item - Image',
						'name' => 'single_featured_item_image',
						'type' => 'image',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_53ebaf621d48b',
						'label' => 'Single Featured Item Supporting Info',
						'name' => 'single_featured_item_supporting_info',
						'type' => 'textarea',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'field_53ebaf7c1d48c',
						'label' => 'Single Featured Item Description',
						'name' => 'single_featured_item_description',
						'type' => 'limiter',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'character_number' => 140,
					),
					array (
						'key' => 'field_53ebaf981d48d',
						'label' => 'Single Featured Item Link URL',
						'name' => 'single_featured_item_link_url',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53ebafab1d48e',
						'label' => 'Single Featured Item Link Text',
						'name' => 'single_featured_item_link_text',
						'type' => 'select',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'Read More ≈' => 'Read More ≈',
							'See More ≈' => 'See More ≈',
							'More Info ≈' => 'More Info ≈',
							'Learn More ≈' => 'Learn More ≈',
							'More Events ≈' => 'More Events ≈',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53ebaa6cb176c',
						'label' => 'Multi-Item Listing',
						'name' => 'listing_style_1-1',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-1-1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53ebaa97b176d',
								'label' => 'Reference Another Post?',
								'name' => 'reference',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_53ebaaaeb176e',
								'label' => 'Reference Post',
								'name' => 'reference_post',
								'type' => 'post_object',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53ebaa97b176d',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'post_type' => array (
									0 => 'post',
									1 => 'resources',
								),
								'taxonomy' => array (
									0 => 'all',
								),
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_53ebaaf6b176f',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53ebaa97b176d',
											'operator' => '!=',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53ebab0ab1770',
								'label' => 'Description',
								'name' => 'description',
								'type' => 'limiter',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53ebaa97b176d',
											'operator' => '!=',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'character_number' => 140,
								'displayCount' => 1,
							),
							array (
								'key' => 'field_53ebab1eb1771',
								'label' => 'Link Url',
								'name' => 'link_url',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53ebaa97b176d',
											'operator' => '!=',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53ebab30b1772',
								'label' => 'Link Text',
								'name' => 'link_text',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'Read More ≈' => 'Read More ≈',
									'See More ≈' => 'See More ≈',
									'More Info ≈' => 'More Info ≈',
									'Learn More ≈' => 'Learn More ≈',
									'More Events ≈' => 'More Events ≈',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => 'Add Entry',
					),
					array (
						'key' => 'field_53e929ff5b302',
						'label' => 'Field Link',
						'name' => 'field_link',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e92a1b5b303',
						'label' => 'Listing Title',
						'name' => 'listing_title',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e92a245b304',
						'label' => 'Urls',
						'name' => 'urls',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53e92a465b305',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53e92a505b306',
								'label' => 'URL',
								'name' => 'url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => 10,
						'layout' => 'table',
						'button_label' => 'Add Link',
					),
					array (
						'key' => 'field_53ea200dc4991',
						'label' => 'Curated Listing',
						'name' => 'listing_style_4',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-4',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53ea2031c4992',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'column_width' => 25,
								'save_format' => 'id',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_53ea2050c4993',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => 37,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53ea2061c4994',
								'label' => 'Author',
								'name' => 'author',
								'type' => 'text',
								'column_width' => 38,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Entry',
					),
				),
				'row_min' => '',
				'row_limit' => 6,
				'layout' => 'row',
				'button_label' => 'Add Widget',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/1-tpl.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
	register_field_group(array (
		'id' => 'acf_four-column-fields-right',
		'title' => 'Four Column Fields - Right',
		'fields' => array (
			array (
				'key' => 'field_53ebbcecdb879',
				'label' => 'Four Column Widgets',
				'name' => 'four_column_widgets-right',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53e928333478c',
						'label' => 'Field Type',
						'name' => 'field_type',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'single-featured' => 'Single Featured',
							'listing-style-1-1' => 'Multi-Item Listing',
							'listing-style1-2' => 'Link Listing',
							'listing-style-2-1' => 'Calendar Feed',
							'listing-style-2-2' => 'Discussion Listing',
							'listing-style-3' => 'Listing Style 3',
							'listing-style-4' => 'Curated Listing',
							'vertical-block' => 'Vertical Block',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53e9287a3478d',
						'label' => 'Field Title',
						'name' => 'field_title',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-1-1',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-3',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-4',
								),
							),
							'allorany' => 'any',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53ea14cf2c28c',
						'label' => 'Field Color',
						'name' => 'field_color',
						'type' => 'radio',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-1-1',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-3',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-4',
								),
							),
							'allorany' => 'any',
						),
						'column_width' => '',
						'choices' => array (
							'blue' => 'Blue',
							'red' => 'Red',
							'green' => 'Green',
							'yellow' => 'Yellow',
							'grey' => 'Grey',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_53e928d334794',
						'label' => 'Single Featured Item Title',
						'name' => 'single_featured_item',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e9290134795',
						'label' => 'Single Featured Item - Image',
						'name' => 'single_featured_item_image',
						'type' => 'image',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_53ebaf621d48b',
						'label' => 'Single Featured Item Supporting Info',
						'name' => 'single_featured_item_supporting_info',
						'type' => 'textarea',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'field_53ebaf7c1d48c',
						'label' => 'Single Featured Item Description',
						'name' => 'single_featured_item_description',
						'type' => 'limiter',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'character_number' => 140,
					),
					array (
						'key' => 'field_53ebaf981d48d',
						'label' => 'Single Featured Item Link URL',
						'name' => 'single_featured_item_link_url',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53ebafab1d48e',
						'label' => 'Single Featured Item Link Text',
						'name' => 'single_featured_item_link_text',
						'type' => 'select',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'single-featured',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'Read More ≈' => 'Read More ≈',
							'See More ≈' => 'See More ≈',
							'More Info ≈' => 'More Info ≈',
							'Learn More ≈' => 'Learn More ≈',
							'More Events ≈' => 'More Events ≈',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53ebaa6cb176c',
						'label' => 'Multi-Item Listing',
						'name' => 'listing_style_1-1',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-1-1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53ebaa97b176d',
								'label' => 'Reference Another Post?',
								'name' => 'reference',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_53ebaaaeb176e',
								'label' => 'Reference Post',
								'name' => 'reference_post',
								'type' => 'post_object',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53ebaa97b176d',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'post_type' => array (
									0 => 'post',
									1 => 'resources',
								),
								'taxonomy' => array (
									0 => 'all',
								),
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_53ebaaf6b176f',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53ebaa97b176d',
											'operator' => '!=',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53ebab0ab1770',
								'label' => 'Description',
								'name' => 'description',
								'type' => 'limiter',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53ebaa97b176d',
											'operator' => '!=',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'character_number' => 140,
								'displayCount' => 1,
							),
							array (
								'key' => 'field_53ebab1eb1771',
								'label' => 'Link Url',
								'name' => 'link_url',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53ebaa97b176d',
											'operator' => '!=',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53ebab30b1772',
								'label' => 'Link Text',
								'name' => 'link_text',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'Read More ≈' => 'Read More ≈',
									'See More ≈' => 'See More ≈',
									'More Info ≈' => 'More Info ≈',
									'Learn More ≈' => 'Learn More ≈',
									'More Events ≈' => 'More Events ≈',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => 'Add Entry',
					),
					array (
						'key' => 'field_53e929ff5b302',
						'label' => 'Field Link',
						'name' => 'field_link',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e92a1b5b303',
						'label' => 'Listing Title',
						'name' => 'listing_title',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e92a245b304',
						'label' => 'Urls',
						'name' => 'urls',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style1-2',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53e92a465b305',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53e92a505b306',
								'label' => 'URL',
								'name' => 'url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => 10,
						'layout' => 'table',
						'button_label' => 'Add Link',
					),
					array (
						'key' => 'field_53ea200dc4991',
						'label' => 'Curated Listing',
						'name' => 'listing_style_4',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e928333478c',
									'operator' => '==',
									'value' => 'listing-style-4',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53ea2031c4992',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'column_width' => 25,
								'save_format' => 'id',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_53ea2050c4993',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => 37,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53ea2061c4994',
								'label' => 'Author',
								'name' => 'author',
								'type' => 'text',
								'column_width' => 38,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Entry',
					),
				),
				'row_min' => '',
				'row_limit' => 6,
				'layout' => 'row',
				'button_label' => 'Add Widget',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/1-tpl.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
}
